open pr to cr
ColmanDevClubORG/Countries-React pull request #3
Opened 2024-12-23 15:52 UTC by nadav-cohen11

2024-12-24 15:33 UTC, Tamir198 requested changes
Left you some comments

2024-12-24 15:33 UTC, Tamir198 commented on src/components/Country.jsx
> +    <a href="#" className="country scale-effect" data-country-name="Belize">
Destruct these : 

```js
const Country = ({ card }) => {
  const { flag, name, population, region, capital } = card;

  return (
  
```

2024-12-24 15:33 UTC, Tamir198 commented on src/components/Filter/filter.jsx
> +  const [ displayDropdown, setDisplayDropdown ] = useState(false);
If this is a function that is coming from outside, call it something like `onSearch` so we will know that this is a function and not a variable

2024-12-24 15:33 UTC, Tamir198 commented on src/components/Filter/filter.jsx
> +    setDisplayDropdown(!displayDropdown);
It will be more common to call this `toggleDropdown`. 

Just an opinion tho

2024-12-24 15:33 UTC, Tamir198 commented on src/components/Filter/filter.jsx
> +          />
If you call a function that only calling another funcntion maybe just call `searchValue` directly in here

2024-12-24 15:33 UTC, Tamir198 commented on src/components/Filter/filter.jsx
> +              <li onClick={() => regionValue("africa")}data-region="africa">Africa</li>
You can improve this and avoid code repetition using map : 

```js
const regions = ["all", "africa", "americas", "asia", "europe", "oceania"];

<ul>
  {regions.map((region) => (
    <li
      key={region}
      onClick={() => regionValue(region)}
      data-region={region}
    >
      {"Some value in here"}
    </li>
  ))}
</ul>
```

2024-12-24 15:33 UTC, Tamir198 commented on src/components/Header.jsx
> +        setDispalayDarkMode(!dispalayDarkMode)
is you do `!dispalayDarkMode` maybe call this `toggleDarkMode`?

2024-12-24 15:33 UTC, Tamir198 commented on src/components/Header.jsx
> +        }
Refer to [this](https://stackoverflow.com/a/23663302/8274756). 

You can simplify this by doing this : 

```
useEffect(() => {
    document.body.classList.toggle("dark-theme", displayDarkMode);
}, [displayDarkMode]);
```

2024-12-24 15:33 UTC, Tamir198 commented on src/components/Header.jsx
> +                    </a>
You can save your hardcoded strings into constants folder

2024-12-24 15:33 UTC, Tamir198 commented on src/pages/Home.jsx
> +            country.name.toLowerCase().includes(input) ||
You can use destruction in here and save the `country.property`

2024-12-24 16:46 UTC, nadav-cohen11 reviewed
I’ve made the changes you requested, thanks for the feedback!

2025-01-01 11:46 UTC, nadav-cohen11 commented
Hi,
would like to get a cr for my last commit (adding api endpoint and the modal), i would like know if i implemented in the right way the useCountries that i have created.
thank you !!

2025-02-18 07:50 UTC, closed without merging